name: Arteco Collection Manager CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./arteco-frontend

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: arteco-frontend/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --watchAll=false

    - name pou≈æit build
      run: npm run build

  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./FineArtApi

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

  install-mobile-deps:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./arteco-mobile

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: arteco-mobile/package-lock.json

    - name: Install dependencies
      run: npm install
